export const portfolioData = {
  name: "Aryam Sharma",
  shortName: "Aryam.dev",
  headline: "Backend Engineer (SDE)",
  badge: "{ Backend Engineer }",
  summary:
    "Software Development Engineer with 1.5 years shipping production backend systems. I work on async pipelines, third-party integrations, and the query-and-cache layer that decides whether a feature feels fast.",
  metaDescription:
    "Software Development Engineer with 1.5 years building production backend systems — Django, PostgreSQL, Redis, Celery. Focused on async pipelines, API performance, and systems that hold up under real load.",
  availability: "Available for backend and distributed systems roles",
  location: "Remote, India",
  email: "aryamsharma.dev@gmail.com",
  phone: "+91-6230707124",
  website: "https://aryamsharma.vercel.app",
  resumeViewUrl: "/resume.pdf",
  resumeDownloadUrl: "/resume.pdf",
  socialLinks: [
    { label: "GitHub", href: "https://github.com/aryam643" },
    { label: "LinkedIn", href: "https://www.linkedin.com/in/aryamsharma/" },
    { label: "Email", href: "mailto:aryamsharma.dev@gmail.com" },
    { label: "Website", href: "https://aryamsharma.vercel.app" },
  ],
  roles: [
    "Software Development Engineer",
    "Backend-Focused Full Stack Developer",
    "Software Product Developer",
    "Django & React Builder",
  ],
  stats: [
    { label: "Experience", value: "1.5 years" },
    { label: "Live leads in production", value: "6,000+" },
    { label: "Order updates/sec", value: "100K+" },
    { label: "Production modules owned", value: "10+" },
  ],
  focusAreas: [
    {
      title: "Backend Systems",
      description: "Build Django services, REST APIs, auth flows, and production workflows for customer-facing products.",
      iconKey: "server",
    },
    {
      title: "API Performance",
      description: "Improve response times with PostgreSQL query optimization, indexing strategies, and Redis caching.",
      iconKey: "database",
    },
    {
      title: "Async & Event Pipelines",
      description: "Webhook ingestion, Celery workers, deduplication under concurrent writes, and third-party integrations that fail gracefully.",
      iconKey: "zap",
    },
    {
      title: "Product Delivery",
      description: "Work across frontend, backend, database, and deployment to ship maintainable product features end to end.",
      iconKey: "code",
    },
  ],
  education: {
    school: "Jaypee University of Information Technology",
    degree: "B.Tech in Computer Science Engineering",
    location: "Solan, India",
    period: "Sept. 2021 - May 2025",
    score: "CGPA: 8.66/10.0",
    courses: [
      "Data Structures & Algorithms",
      "Database Management Systems",
      "Computer Networks",
      "Machine Learning",
    ],
  },
  experiences: [
    {
      title: "Software Development Engineer",
      company: "Fellafeeds",
      location: "Remote",
      period: "Sept. 2025 - Present",
      type: "Full-time",
      achievements: [
        "Owned backend development of a large-scale Django-based customer feedback platform, contributing to 10+ production modules including feedback, reviews, visitors, loyalty, referrals, and QR Codes.",
        "Designed REST APIs on top of PostgreSQL and Redis, using query tuning, indexing, and caching to keep response times predictable as usage grew.",
        "Migrated and refactored legacy workflows into scalable Django services, resolving complex PostgreSQL migration issues with zero production data loss.",
        "Implemented Google and social review ingestion pipelines using APIs and OCR, enabling automated review verification and moderation.",
        "Built secure visitor verification and OTP-based authentication flows with nonce validation and rate limiting, reducing fraudulent submissions.",
      ],
      technologies: ["Django", "Python", "PostgreSQL", "Redis", "Celery", "REST APIs", "OCR"],
    },
    {
      title: "Software Product Developer Intern",
      company: "TT Consultants",
      location: "Mohali, India",
      period: "Jan. 2025 - Aug. 2025",
      type: "Internship",
      achievements: [
        "Migrated 3 legacy TCL modules (5,000+ LOC) to Django, improving maintainability by 60% and reducing production bugs.",
        "Built full-stack features with Django REST APIs and PostgreSQL, supporting workflows for 200+ internal users.",
      ],
      technologies: ["Django", "Python", "PostgreSQL", "Django REST Framework", "TCL"],
    },
    {
      title: "React Developer Intern",
      company: "Pragmatic Silicon",
      location: "Noida, India",
      period: "Jun. 2024 - Jul. 2024",
      type: "Internship",
      achievements: [
        "Developed an NLP-based resume parsing system that processed 500+ documents with 92% accuracy.",
        "Built secure authentication and role-based access control for 1,000+ users and integrated Razorpay payment workflows that processed 5,000+ monthly transactions.",
      ],
      technologies: ["React", "JavaScript", "JWT", "Razorpay", "NLP"],
    },
  ],
  projects: [
    {
      name: "Indofast CRM",
      description:
        "A full-stack CRM built solo for a live EV energy client, handling lead ingestion, telephony, and real-time battery inventory across hub and field locations.",
      stack: ["Django", "DRF", "PostgreSQL", "React", "Redis", "Celery", "WebRTC", "Meta Graph API"],
      sourceCode: undefined as string | undefined,
      livePreview: undefined as string | undefined,
      category: "Production System",
      status: "Active",
      note: "Private repository — live production client project",
      iconKey: "server",
      featured: true,
      metrics: ["6,000+ live leads", "Concurrent webhook safety", "RBAC across 3 roles"],
      highlights: [
        "Automated Facebook Lead Ads ingestion through Meta webhooks and Graph API v19.0, with Celery workers handling deduplication and real-time sync.",
        "Built a tiered duplicate-handling policy mapping lead stages (New through Delivered) to field-specific update behavior, with immutable registered_at, a separate sla_clock_started_at, and first-touch/last-touch source attribution.",
        "Used select_for_update to resolve race conditions when concurrent webhooks hit the same lead.",
        "Integrated the Ozonetel Web JS SDK as a WebRTC softphone for in-browser calling, plus Click2Call and inbound webhooks.",
        "Normalized messy Indian city data — typos, pincodes entered as city names, word-order variants — with a rapidfuzz cascade using token_sort_ratio and Jaro-Winkler similarity.",
      ],
      highlightLabel: "Featured build",
      highlightNote:
        "The hardest problems here weren't the CRUD. They were concurrency, dirty input, and third-party APIs that don't behave.",
    },
    {
      name: "BSM: Battery Dispatch & Traceability Portal",
      description:
        "A dispatch and custody-tracking system for EV batteries, modelling allocation as an explicit state machine across four roles and seven stages.",
      stack: ["Django", "DRF", "PostgreSQL", "Redis", "React"],
      sourceCode: undefined as string | undefined,
      livePreview: undefined as string | undefined,
      category: "Production System",
      status: "Active",
      note: "Private repository — live production client project",
      iconKey: "database",
      featured: true,
      metrics: ["7-stage state machine", "4-role permission model", "Partial fulfillment support"],
      highlights: [
        "Designed a 7-stage allocation state machine with 4 distinct roles, supporting partial fulfillment and proof-of-delivery capture.",
        "Built a cascading custody resolver for messy alphanumeric battery IDs — exact match, then suffix match, then GPS proximity — so field scans resolve to the right unit without manual reconciliation.",
        "Modelled custody transfer so every battery has a continuous, auditable chain from hub to field.",
      ],
      highlightLabel: "Featured build",
      highlightNote:
        "State machines are easy to draw and hard to keep honest once partial fulfillment and offline field scans enter the picture.",
    },
    {
      name: "MBP-10 Orderbook Reconstruction",
      description:
        "A high-performance C++17 engine that converts Market-by-Order streams into Market-by-Price snapshots for HFT-style workflows.",
      stack: ["C++17", "STL", "Data Structures", "Unit Testing"],
      sourceCode: "https://github.com/aryam643/Orderbook" as string | undefined,
      livePreview: undefined as string | undefined,
      category: "Systems Programming",
      status: "Active",
      note: undefined as string | undefined,
      iconKey: "zap",
      featured: true,
      metrics: ["100K+ updates/sec", "O(log n) price-level ops", "Sequence gap detection"],
      highlights: [
        "Processes 100,000+ order updates per second with price-level aggregation via ordered maps at O(log n) insert/update.",
        "Sequence gap integrity checks catch out-of-order and dropped messages before they corrupt book state.",
        "Memory-optimized order tracking with minimal heap allocation on the hot path.",
      ],
      highlightLabel: "Featured build",
      highlightNote: "The one project where the constraint is the clock, not the requirements.",
    },
    {
      name: "Real-Time Collaborative Whiteboard",
      description:
        "A multi-user whiteboard built with React, Node.js, and WebSockets for synchronized drawing sessions and low-latency collaboration.",
      stack: ["React", "Node.js", "WebSockets", "Canvas API", "MongoDB"],
      sourceCode: "https://github.com/aryam643/white_board" as string | undefined,
      livePreview: "https://drive.google.com/file/d/1bE0B6OLID62vj6j7E5fObxuvIBXIQxWE/view?usp=sharing" as string | undefined,
      category: "Real-time System",
      status: "Active",
      note: undefined as string | undefined,
      iconKey: "users",
      featured: false,
      metrics: ["50+ concurrent users", "Sub-100ms sync", "Conflict resolution"],
      highlights: undefined as string[] | undefined,
      highlightLabel: "Why it's here",
      highlightNote:
        "Concurrent state across many clients, where the correctness bar is whether two people drawing at once still see the same canvas.",
    },
  ],
  skillGroups: [
    {
      title: "Languages",
      items: ["Python", "C++", "SQL", "JavaScript", "TypeScript", "Bash"],
    },
    {
      title: "Backend",
      items: ["Django", "Django REST Framework", "Celery", "FastAPI", "Flask", "Node.js", "Express.js"],
    },
    {
      title: "Databases",
      items: ["PostgreSQL", "Redis", "MySQL", "MongoDB", "SQLite"],
    },
    {
      title: "Frontend",
      items: ["React", "Next.js", "TypeScript", "Redux", "Tailwind CSS"],
    },
    {
      title: "Infrastructure & Tools",
      items: ["AWS (EC2, S3, Lambda)", "Docker", "Nginx", "Jenkins", "GitHub Actions", "Git", "Postman"],
    },
    {
      title: "Integrations",
      items: ["WebRTC", "WebSockets", "Meta Graph API", "Ozonetel", "OCR pipelines"],
    },
  ],
} as const
